version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_db
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    networks:
      - blog_network

  web:
    build: .
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: blog_db
    
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Порт приложения открыт
    depends_on:
      - db
    restart: always
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge
